#!/bin/bash
level4_pass="password";

touch README.txt

count=0;
while [ $count -lt 100 ];
do
        echo "junk"$count > oneline.txt;
        cat README.txt oneline.txt > README2.txt
        rm README.txt
        mv README2.txt README.txt
        count=$(($count+1));
done
